### ISSUE TITLE
Update info about version

### ISSUE THREAD

**Issue by sp2ong** [DVSwitch/MMDVM_Bridge#3]
Hi Steve

When you compile the new version of MMDVM_Bridge, please update the information in the code with the version information from 20180423 to the current one and maybe MMDVM_Bridge will send PACKAGE_ID information in HBP, e.g. MMDVM_BRIDGE?

Waldek

**Comment by N4IRS** [comment]
I'll put it on the list.
Are you actually testing for those values somewhere or is it cosmetic?

Steve N4IRS
